name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  all:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/versions.gradle') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/versions.gradle') }}
            ${{ runner.os }}-gradle-

      - name: Assemble
        run: ./gradlew --no-daemon clean spotlessCheck build

      - name: Store distribution artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distributions
          path: build/distributions

      - name: Check Dockerfile syntax
        run: |
          docker run --rm -i hadolint/hadolint < docker/openjdk-17/Dockerfile
      - name: Build Docker Image
        run: |
          ./gradlew dockerDist

      - name: Login to Docker Hub for self hosted
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_RW }}
          password: ${{ secrets.DOCKER_PAT_RW }}
      - name: Publish Docker Image
        run: |
          ./gradlew --no-daemon dockerUpload

      - name: Publish Multi-arch Docker Image
        run: |
          ./gradlew --no-daemon dockerManifest
